"""p2 tasknode queue fields

Revision ID: ee654d8ed570
Revises: 59256eb92346
Create Date: 2026-09-14 19:57:46.178394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee654d8ed570'
down_revision: Union[str, Sequence[str], None] = '59256eb92346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_nodes', sa.Column('depends_on', sa.JSON(), nullable=True))
    op.add_column('task_nodes', sa.Column('payload', sa.JSON(), nullable=True))
    op.add_column('task_nodes', sa.Column('worker_id', sa.String(length=64), nullable=True))
    op.add_column('task_nodes', sa.Column('attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('task_nodes', sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('task_nodes', sa.Column('lease', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_nodes', 'lease')
    op.drop_column('task_nodes', 'queued_at')
    op.drop_column('task_nodes', 'attempts')
    op.drop_column('task_nodes', 'worker_id')
    op.drop_column('task_nodes', 'payload')
    op.drop_column('task_nodes', 'depends_on')
    # ### end Alembic commands ###
